apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-github-workflow-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 767398147229.dkr.ecr.us-east-1.amazonaws.com/gitworkflowrepo:20240606123849
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

